import type { Route } from "../types";

/**
 * Test route fixture mirroring seeded platform.routes plus legacy IDs relied on
 * by static body/rate-limit test defaults.
 */
export const TEST_ROUTES: Route[] = [
  {
    id: "me-1",
    method: "GET",
    pathPattern: "/me",
    targetPath: "/me",
    serviceKey: "accounts-service",
    actionKey: "accounts.me.getOrCreate",
    workspaceScoped: false,
    isPublic: false,
  },
  {
    id: "workspaces-1",
    method: "GET",
    pathPattern: "/workspaces",
    targetPath: "/workspaces",
    serviceKey: "accounts-service",
    actionKey: "accounts.workspaces.listForUser",
    workspaceScoped: false,
    isPublic: false,
  },
  {
    id: "workspaces-2",
    method: "POST",
    pathPattern: "/workspaces",
    targetPath: "/workspaces",
    serviceKey: "accounts-service",
    actionKey: "accounts.workspaces.create",
    workspaceScoped: false,
    isPublic: false,
  },
  {
    id: "workspaces-members-1",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/members",
    targetPath: "/workspaces/:workspaceId/members",
    serviceKey: "accounts-service",
    actionKey: "accounts.workspace_members.listForWorkspace",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "invites-1",
    method: "POST",
    pathPattern: "/workspaces/:workspaceId/invites",
    targetPath: "/workspaces/:workspaceId/invites",
    serviceKey: "accounts-service",
    actionKey: "accounts.invites.create",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "invites-2",
    method: "GET",
    pathPattern: "/workspace-invites/:token",
    targetPath: "/workspace-invites/:token",
    serviceKey: "accounts-service",
    actionKey: "accounts.invites.resolve",
    workspaceScoped: false,
    isPublic: true,
  },
  {
    id: "invites-3",
    method: "POST",
    pathPattern: "/workspace-invites/:token/accept",
    targetPath: "/workspace-invites/:token/accept",
    serviceKey: "accounts-service",
    actionKey: "accounts.invites.accept",
    workspaceScoped: false,
    isPublic: false,
  },
  {
    id: "1",
    method: "POST",
    pathPattern: "/workspaces/:workspaceId/documents",
    targetPath: "/documents",
    serviceKey: "doc-service",
    actionKey: "docs.document.create",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "2",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/documents/:id",
    targetPath: "/documents/:id",
    serviceKey: "doc-service",
    actionKey: "docs.document.read",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "3",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/blog",
    targetPath: "/blog",
    serviceKey: "cms-core",
    actionKey: "cms.blog_entry.listPublished",
    workspaceScoped: true,
    isPublic: true,
  },
  {
    id: "4",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/blog/:slug",
    targetPath: "/blog/:slug",
    serviceKey: "cms-core",
    actionKey: "cms.blog_entry.getPublishedBySlug",
    workspaceScoped: true,
    isPublic: true,
  },
  {
    id: "7",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/content/:routeSegment",
    targetPath: "/content/:routeSegment",
    serviceKey: "cms-core",
    actionKey: "cms.content.listPublished",
    workspaceScoped: true,
    isPublic: true,
  },
  {
    id: "8",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/content/:routeSegment/:slug",
    targetPath: "/content/:routeSegment/:slug",
    serviceKey: "cms-core",
    actionKey: "cms.content.getPublishedBySlug",
    workspaceScoped: true,
    isPublic: true,
  },
  {
    id: "5",
    method: "POST",
    pathPattern: "/workspaces/:workspaceId/content-entries/:entryId/comments",
    targetPath: "/content-entries/:entryId/comments",
    serviceKey: "cms-core",
    actionKey: "cms.comments.create",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "6",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/content-entries/:entryId/comments",
    targetPath: "/content-entries/:entryId/comments",
    serviceKey: "cms-core",
    actionKey: "cms.comments.listForEntry",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "telemetry-1",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/telemetry/events",
    targetPath: "/workspaces/:workspaceId/telemetry/events",
    serviceKey: "telemetry-service",
    actionKey: "telemetry.events.listRecentForWorkspace",
    workspaceScoped: true,
    isPublic: false,
  },
  {
    id: "telemetry-2",
    method: "GET",
    pathPattern: "/workspaces/:workspaceId/telemetry/stats/routes",
    targetPath: "/workspaces/:workspaceId/telemetry/stats/routes",
    serviceKey: "telemetry-service",
    actionKey: "telemetry.stats.summaryByRoute",
    workspaceScoped: true,
    isPublic: false,
  },
];
